print("Welcome to the Division Calculator")
print("This Calculator divides two numbers given by the user.")
print("Enter a number")
x=int(input())
print("Enter another number")
y=int(input())
print("Your answer is:")
print(x/y)
